const ACTION_TYPES = {
    SET_PACKAGES: "SET_PACKAGES",
    SET_CUSTOMERS: "SET_CUSTOMERS",
    ADD_PACKAGE: "ADD_PACKAGE",
    REMOVE_PACKAGE: "REMOVE_PACKAGE",
    REMOVE_CUSTOMER: "REMOVE_CUSTOMER",
};

export default ACTION_TYPES;